// Health centers data
const healthCentersData = [
    {
        id: 1,
        name: "Mulago National Referral Hospital",
        type: "hospital",
        lat: 0.3476,
        lng: 32.5825,
        contact: "+256-414-532-000",
        emergency: "+256-414-532-001",
        services: ["Emergency Care", "Surgery", "Maternity", "Pediatrics", "ICU", "Cardiology", "Oncology"],
        description: "Uganda's largest public hospital and main teaching hospital",
        address: "Mulago Hill Road, Kampala",
        hours: "24/7 Emergency Services",
        hasEmergency: true
    },
    {
        id: 2,
        name: "International Hospital Kampala",
        type: "hospital",
        lat: 0.3174,
        lng: 32.6089,
        contact: "+256-414-342-000",
        emergency: "+256-414-342-111",
        services: ["Cardiology", "Oncology", "Orthopedics", "Neurology", "Pediatrics", "Maternity"],
        description: "Leading multi-specialty private hospital",
        address: "Namuwongo Road, Kampala",
        hours: "24/7",
        hasEmergency: true
    },
    {
        id: 3,
        name: "Kampala Hospital",
        type: "hospital",
        lat: 0.3224,
        lng: 32.5856,
        contact: "+256-414-289-600",
        services: ["General Medicine", "Surgery", "Maternity", "Pediatrics", "Laboratory"],
        description: "Modern private healthcare facility",
        address: "Acacia Avenue, Kololo",
        hours: "24/7",
        hasEmergency: true
    },
    {
        id: 4,
        name: "Nsambya Hospital",
        type: "hospital",
        lat: 0.2856,
        lng: 32.5878,
        contact: "+256-414-267-011",
        services: ["General Practice", "Surgery", "Pediatrics", "Maternity", "Emergency Care"],
        description: "St. Francis Hospital Nsambya",
        address: "Nsambya Road, Kampala",
        hours: "24/7 Emergency",
        hasEmergency: true
    },
    {
        id: 5,
        name: "Kisenyi Health Center IV",
        type: "health-center",
        lat: 0.3158,
        lng: 32.5723,
        contact: "+256-414-235-678",
        services: ["Outpatient Care", "Maternity", "Immunization", "Laboratory", "Pharmacy"],
        description: "Public health center serving central Kampala",
        address: "Kisenyi, Central Division",
        hours: "7:00 AM - 9:00 PM",
        hasEmergency: false
    },
    {
        id: 6,
        name: "Kiswa Health Clinic",
        type: "clinic",
        lat: 0.2987,
        lng: 32.6123,
        contact: "+256-414-567-890",
        services: ["Basic Healthcare", "Immunization", "Prenatal Care", "Family Planning"],
        description: "Community clinic serving Kiswa area",
        address: "Kiswa, Nakawa Division",
        hours: "8:00 AM - 6:00 PM",
        hasEmergency: false
    },
    {
        id: 7,
        name: "Kawempe General Hospital",
        type: "hospital",
        lat: 0.3822,
        lng: 32.5675,
        contact: "+256-414-692-000",
        services: ["Emergency", "Surgery", "Maternity", "Pediatrics", "Laboratory"],
        description: "Public hospital serving Kawempe Division",
        address: "Kawempe, Kampala",
        hours: "24/7 Emergency",
        hasEmergency: true
    },
    {
        id: 8,
        name: "Mengo Hospital",
        type: "hospital",
        lat: 0.2972,
        lng: 32.5600,
        contact: "+256-414-274-873",
        services: ["General Practice", "Surgery", "Maternity", "Pediatrics"],
        description: "Private hospital with historical significance",
        address: "Mengo, Kampala",
        hours: "24/7",
        hasEmergency: true
    },
    {
        id: 9,
        name: "Rubaga Hospital",
        type: "hospital",
        lat: 0.3044,
        lng: 32.5492,
        contact: "+256-414-270-623",
        services: ["Maternity", "Surgery", "Pediatrics", "Pharmacy", "Laboratory"],
        description: "Private hospital on Rubaga Hill",
        address: "Rubaga, Kampala",
        hours: "24/7",
        hasEmergency: true
    },
    {
        id: 10,
        name: "Kampala Capital City Authority Clinic",
        type: "clinic",
        lat: 0.3163,
        lng: 32.5822,
        contact: "+256-414-258-641",
        services: ["General outpatient care", "Immunization", "Health Education"],
        description: "Public clinic operated by KCCA",
        address: "City Hall, Kampala",
        hours: "8:00 AM - 5:00 PM",
        hasEmergency: false
    }
];